config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root 'home#index'
  get 'contact', to: 'home#contact'
  get 'menu', to: 'home#menu'
  get 'search', to: 'home#search',  as: :search
  resources :foods
  post 'foods/:id/order(.:format)', to: 'foods#order',  as: :food_order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :menu_id, presence: true

  belongs_to :menu
  has_and_belongs_to_many :orders

  def show_image
    return self.image_url ? self.image_url : 'http://placehold.it/350x150'
  end

end

app/models/menu.rb
class Menu < ApplicationRecord
    validates :name, presence: true, uniqueness: {case_sensitive: false}

    has_many :foods

    def self.run_seed
        %w(Breakfast Lunch Dinner Drinks).each do |menuName|
            Menu.find_or_create_by(name: menuName)
        end
    end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, presence: true
  validates :phone, presence: true
  validates :address, presence: true

  has_and_belongs_to_many :foods

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
    session[:order] = nil
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food.update_attributes(:view => @food.view + 1)
  end

  # GET /foods/new
  def new
    @food = Food.new
    @menus = Menu.all
  end

  # GET /foods/1/edit
  def edit
    @menus = Menu.all
  end

  def order
    if (session[:order] == nil)
      session[:order] = []
    end

    session[:order].push({id: params[:food_id], total: 22})
    redirect_to new_order_path()
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)
    @menus = Menu.all

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, locals: {menus: Menu.all} }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :price, :menu_id, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact

  end

  def menu
    menu = Menu.find_by(name: params[:section])
    @foods = menu ? menu.foods : []
  end

  def search
    if (params[:query])
      query = params[:query]
      @foods = Food.where("name ILIKE ?","%#{query}%")
    else
      @foods = Food.all
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show

    @foods = @order.foods

  end

  # GET /orders/new
  def new
    @order = Order.new

    @foods = self.get_placed_foods
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @foods = self.get_placed_foods

    @foods.each do |food|
       @order.foods << food
    end

    respond_to do |format|
      if @order.save

        # Reset session
        session[:order] = []

        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_placed_foods
    foodIds = Array.new()
    session[:order].each do |food|
      foodIds.push(food["id"])
    end

    return Food.find(foodIds)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active(controller, action)
      params[:action] == action && params[:controller] == controller ? "active" : nil
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foods/_form.html.erb
<%= form_for(food) do |f| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :menu_id %>
    <%= f.select :menu_id,
        options_from_collection_for_select(@menus, 'id', 'name', @food.menu_id),
        {prompt: 'Select Menu'},
        {class: 'form-control', required: true} %>
  </div>

  <div class="form-group">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>

  <div class="actions text-xs-center">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="card">
  <div class="card-header clearfix">
    <h2 class="pull-xs-left">Editing Food</h2>
    <div class="pull-xs-right">
      <%= link_to 'Show', @food, class: "btn btn-info" %>
      &nbsp;
      <%= link_to 'Back', foods_path, class: "btn btn-warning" %>
    </div>
  </div>
  <div class="card-block">
    <%= render 'form', food: @food, menus: @menus %>
  </div>
</div>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header clearfix">
    <h2 class="pull-xs-left">Foods</h2>
    <div class="pull-xs-right">
      <%= link_to 'New Food', new_food_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="card-block">
    <table class="table table-striped table-foods">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Menu</th>
          <th>Image</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr class="food">
            <td><%= food.name %></td>
            <td><%= food.description %></td>
            <td><%= food.price %></td>
            <td><%= food.menu.name %></td>
            <td><%= image_tag(food.show_image()) %></td>
            <td><%= link_to 'Show', food %></td>
            <td><%= link_to 'Edit', edit_food_path(food) %></td>
            <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="card">
  <div class="card-header clearfix">
    <h2 class="pull-xs-left">New Food</h2>
    <div class="pull-xs-right">
      <%= link_to 'Back', foods_path, class: "btn btn-info" %>
    </div>
  </div>
  <div class="card-block">
    <%= render 'form', food: @food, menus: @menus %>
  </div>
</div>

app/views/foods/show.html.erb
<div class="card">
  <div class="card-header clearfix">
    <h2 class="pull-xs-left"><strong><%= @food.menu.name %> / <%= @food.name %></strong></h2>
    <div class="pull-xs-right">
      <%= link_to "Back",
          request.referer.present? ? request.referer : menu_path(params: {section: @food.menu.name}),
          class: "btn btn-warning" %>
    </div>
  </div>
  <div class="card-block">

    <% if notice %>
      <p class="alert alert-success" role="alert"><%= notice %></p>
    <% end %>

    <div class="row">

      <div class="col-xs-12 col-md-6">

        <fieldset>
          <div class="form-group">
            <label><strong>Name:</strong></label>
            <p><%= @food.name %></p>
          </div>

          <div class="form-group">
            <label><strong>Description:</strong></label>
            <p><%= @food.description %></p>
          </div>

          <div class="form-group">
            <label><strong>Price:</strong></label>
            <p><%= number_to_currency(@food.price, unit: "VND ") %></p>
          </div>

          <div class="form-group">
            <label><strong>Menu:</strong></label>
            <p><%= @food.menu.name %></p>
          </div>
        </fieldset>

        <hr>

        <fieldset>
          <div class="form-group">
            <label><strong>Total view:</strong></label>
            <p><span class="tag tag-pill tag-success"><%= @food.view %></span></p>
          </div>
        </fieldset>

      </div>

      <div class="col-xs-12 col-md-6">
        <div class="form-group">
          <label><strong>Image:</strong></label>
          <p><%= image_tag(@food.show_image(), class: "img-fluid img-thumbnail") %></p>
        </div>
      </div>

    </div>

    <hr>

    <%= form_tag(food_order_path(id: @food.id), method: "post", class: "text-xs-center") do %>
      <%= hidden_field_tag(:food_id, @food.id) %>
      <%= submit_tag("Order", class: "btn btn-danger") %>
    <% end %>

  </div>
</div>

app/views/home/contact.html.erb
<section class="page-intro">
    <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit ? </h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis quasi consectetur
    aspernatur consequatur, modi nulla, nesciunt obcaecati nihil cumque labore dolorem temporibus
    beatae. Repellat unde mollitia modi, numquam recusandae dicta.<br>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis quasi consectetur
    aspernatur consequatur, modi nulla, nesciunt obcaecati nihil cumque labore dolorem temporibus
    beatae. Repellat unde mollitia modi, numquam recusandae dicta.</p>
</section>

<hr>

<div class="row">
    <div class="col-md-6 col-xs-12">
        <div id="contact-map"></div>
    </div>
    <div class="col-md-6 col-xs-12">
        <p class="hidden-md-up"></p>
        <address>
            <strong>GAU Restaurant</strong> <br>
            141 Truong Dinh, Hai Ba Trung, Hanoi <br>
            Contact at : 04354533455
        </address>
    </div>
</div>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "contact" %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to Gau Restaurant</h1>
<h2>One of the most famous Vietnamese traditional restaurant in Vietnam</h2>

<hr>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img src="https://cdn0.vox-cdn.com/thumbor/7KlR-Ig1j3IBw1Pc2732XBeMBIE=/0x302:5760x3542/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/42127168/bourdain-vietnam-opener.0.0.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img src="https://i.ytimg.com/vi/bAVWi-Ww43s/maxresdefault.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img src="http://4.bp.blogspot.com/-WZlrRwSaSr0/VbuxGAerVpI/AAAAAAAAJps/WSX2yUYmoRg/s1600/C360_2015-07-26-20-44-43-665.jpg" alt="Third slide">
    </div>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia totam quod ipsam impedit error cupiditate debitis deserunt sit. Quis, dolore, ipsam. Reprehenderit nulla iusto architecto minus excepturi incidunt quod, harum.</p>

<hr>

app/views/home/menu.html.erb
<section class="intro">
  <h2>Our Menu</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</section>

<ul class="nav nav-tabs">
  <% Menu.all.each do |menu| %>
    <li class="nav-item">
      <%= link_to menu.name, menu_path(section: menu.name),
          class: "nav-link #{'active' if params[:section] == menu.name}" %>
    </li>
  <% end %>
</ul>

<% if !@foods.empty? %>
  <table class="table table-striped table-foods" id="table-foods-menu">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Total view</th>
        <th>Image</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr class="food" data-url="<%= food_path(food) %>">
          <td><%= food.name %></td>
          <td><%= food.price %></td>
          <td><span class="tag tag-pull tag-success"><%= food.view %></span></td>
          <td><%= image_tag(food.show_image()) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

<% content_for :javascript_includes do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('#table-foods-menu').DataTable({
        "bFilter": false,
        // "bPaginate": false,
        "bLengthChange": false,
        "pageLength": 5,
        "bInfo" : false
      });
      $('#table-foods-menu tbody').on( 'click', 'tr', function () {
        var url = $(this).data('url');
        window.location.href=url;
      });
    });
  </script>
<% end %>

app/views/home/search.html.erb
<section class="intro">
  <h2>Your search result</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</section>

<% if !@foods.empty? %>
  <table class="table table-striped table-foods" id="table-foods-menu">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Image</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr class="food" data-url="<%= food_path(food) %>">
          <td><%= food.name %></td>
          <td><%= food.price %></td>
          <td><%= image_tag(food.show_image()) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

<% content_for :javascript_includes do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('#table-foods-menu').DataTable({
        "bFilter": false,
        // "bPaginate": false,
        "bLengthChange": false,
        "pageLength": 5,
        "bInfo" : false
      });
      $('#table-foods-menu tbody').on( 'click', 'tr', function () {
        var url = $(this).data('url');
        window.location.href=url;
      });
    });
  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded navbar-main">
  <div class="container">
    <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">
      &#9776;
    </button>
    <div class="collapse navbar-toggleable-xs" id="navbar-header">
      <a class="navbar-brand" href="/">GAU Restaurant</a>
      <ul class="nav navbar-nav">
        <li class="nav-item <%= is_active('home', 'index') %>">
          <a class="nav-link" href="/">Home</a></li>
        <li class="nav-item <%= is_active('home', 'menu') %>">
          <a class="nav-link" href="/menu?section=Breakfast">Menu</a>
        </li>
        <li class="nav-item <%= is_active('home', 'contact') %>">
          <a class="nav-link" href="/contact">Contact Us</a>
        </li>
        <% if session[:order] != nil && !session[:order].empty? %>
          <li class="nav-item">
            <%= link_to 'My Order', new_order_path , class:"btn btn-outline-danger" %>
          </li>
        <% end %>
      </ul>
      <%= form_tag("/search", method: "get", class: "form-inline pull-xs-right", id: "search-food-form") do %>
        <%= text_field_tag 'query', params[:query],
            placeholder: "Search food by name",
            class: 'form-control' %>
        <%= button_tag("Search", class: "btn btn-outline-success") %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaures</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAnAjX5ZNh-hfz2NOQSatoPxIphgaC-0UY" %>
    <%= javascript_include_tag "https://hpneo.github.io/gmaps/gmaps.js" %>
    <%= yield :javascript_includes %>
  </head>

  <body>

    <!-- Navbar -->
    <%= render "layouts/navbar" %>

    <!-- Main Container -->
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/orders/_foods.html.erb
<table class="table table-striped table-foods">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr class="food">
        <td><%= food.name %></td>
        <td><%= food.price %></td>
      </tr>
    <% end %>
    <tr>
      <td>Shipping fee</td>
      <td>20000.0</td>
    </tr>
  </tbody>
</table>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, class: "form-control" %>
  </div>

  <div class="actions text-xs-center">
    <%= f.submit "Confirm", class: "btn btn-primary" %>
    <%= link_to "Order more ?", menu_path %>
  </div>

<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.phone %></td>
        <td><%= order.address %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="card">
  <div class="card-header clearfix">
    <h2 class="pull-xs-left">New Order</h2>
    <div class="pull-xs-right">
      <!-- <%= link_to 'Back', menu_path, class: "btn btn-info" %> -->
    </div>
  </div>
  <div class="card-block">
    <%= render 'foods', foods: @foods %>

    <%= render 'form', order: @order %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="card">
  <div class="card-header clearfix">
    <h2 class="pull-xs-left">
      <strong>Order : # <%= @order.id %></strong> -
      Created at <%= @order.created_at.to_formatted_s(:long_ordinal) %>
    </h2>
    <div class="pull-xs-right">
      <%= link_to "Back", menu_path, class: "btn btn-warning" %>
    </div>
  </div>
  <div class="card-block">

    <% if notice %>
      <p class="alert alert-success" role="alert"><%= notice %></p>
    <% end %>

    <div class="row">

      <div class="col-xs-12 col-md-6">
        <div class="form-group">
          <label><strong>Name:</strong></label>
          <p><%= @order.name %></p>
        </div>

        <div class="form-group">
          <label><strong>Phone:</strong></label>
          <p><%= @order.phone %></p>
        </div>

        <div class="form-group">
          <label><strong>Address</strong></label>
          <p><%= @order.address %></p>
        </div>
      </div>

      <div class="col-xs-12 col-md-6">
        <%= render 'foods', foods: @foods %>
      </div>

    </div>
  </div>
</div>